services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: obelisk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: obelisk_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db # Uses the service name as the hostname
      - DB_PORT=5432
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - DB_NAME=obelisk

volumes:
  postgres_data: